Add sections for evals and use cases; cite evals appropriate; update methods considered table
w3c/did-rubric pull request #50
Opened 2021-09-07 20:26 UTC by dhh1128

2021-09-07 22:19 UTC, TallTed commented on index.html
> +          <td>Evaluations written by Daniel Hardman, to illusfor this rubric. Not explicitly funded.</td>
```suggestion
          <td>Evaluations written by Daniel Hardman, to illustrate this rubric. Not explicitly funded.</td>
```

2021-09-07 22:21 UTC, TallTed commented on index.html
> +              the Web of Trust</cite>. Published 2020-07020. <a
```suggestion
              the Web of Trust</cite>. Published 2020-07-20. <a
```

2021-09-07 22:22 UTC, TallTed commented on index.html
> +            Not explicitly funded.</td>
```suggestion
          <td>The original DID Rubric paper from Rebooting the Web of Trust. Not explicitly funded.</td>
```

2021-09-20 18:55 UTC, jandrieu commented
@dhh1128 Looks like we have an error in the CI/CD tooling. It is likely because of a couple of missing <ol> tags (at least I had that problem on the registry PR and your PR likely has the same cruft). You can probably identify the error location by finding a </p> tag followed by a <li> tag. At least that helped with the instances I had fixed.

Alternatively, merge in #49 and pull main back into your PR. That would probably clean it up with less likelihood of a merge conflict.

2021-09-20 21:11 UTC, TallTed commented
@jandrieu -- You need to codefence the HTML tags in [your comment](https://github.com/w3c/did-rubric/pull/50#issuecomment-923191375), to make them visible to readers.

2021-10-29 22:43 UTC, rxgrant commented
This is stumping the editors and blocking other merges and action right now.

2021-10-29 22:54 UTC, rxgrant requested changes

2021-10-29 22:54 UTC, rxgrant commented on index.html
> +        Did:jlinc
Did:jlinc here looks wrong

2021-10-29 22:54 UTC, rxgrant commented on index.html
> +            did:twit
did:twit duplicated.  breaking build.

2021-10-29 23:05 UTC, TallTed commented on index.html
> +            did:twit
```suggestion
        <tr id="did:pkh">
          <td>
            did:pkh
```

2021-10-29 23:06 UTC, TallTed commented on index.html
>        </table>
```suggestion
        </tr>
      </table>
```

2021-10-29 23:07 UTC, TallTed requested changes
I believe my two suggested changes will resolve the build error, and remove a tiny errant snippet of text.

2021-11-01 09:22 UTC, dhh1128 commented on index.html
>        </table>
Updated and credit you. Thanks.

2021-11-01 09:22 UTC, dhh1128 commented on index.html
> +            did:twit
Updated and credited you.

2021-11-01 09:22 UTC, dhh1128 commented on index.html
> +        Did:jlinc
Agreed. Fixed. thanks.

2021-11-01 09:22 UTC, dhh1128 commented on index.html
> +            did:twit
Updated and fixed.

2021-11-02 18:28 UTC, rxgrant approved these changes
changes look good.

2021-11-02 18:34 UTC, jandrieu commented
This looks good. Merging.

2021-11-02 18:34 UTC, merged

2021-11-16 16:39 UTC, jandrieu commented
Looks like the edits from this merge got smushed.

@rxgrant Let's review and figure out how to get the evaluation citations and related metadata back into the document.

2021-11-16 20:22 UTC, jandrieu commented
@rxgrant and I found that this was a synchronization problem between the main branch, the github.io version, and the /TR version.

We removed the hardcoded publication date (August 26) from the index.html and that eventually got us an updated github.io page, but the TR has not yet updated. 

We're going to give it another day to see if the TR updates, but we are also baffled as to why the date in the html would prevent github pages from rendering a new .io page.  When we removed the date, it didn't just give us the correct date, it actually pulled in the latest version. How and why that happens seems to be buried in the github pages configuration.

@iherman Can you advise about how we should be doing this? I think we aren't quite configured right for auto publishing and I expect our hack of removing the date may not be the "right" way.

2021-11-17 08:33 UTC, iherman commented
> @iherman Can you advise about how we should be doing this? I think we aren't quite configured right for auto publishing and I expect our hack of removing the date may not be the "right" way.

There seem to be some system problems. I have updated the github action script but that did not solve all the issues. See my [mail](https://lists.w3.org/Archives/Public/spec-prod/2021OctDec/0056.html) sent to the powers to be (I cc-d you because I was not sure that you can access that archive).

Sigh...